global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 0.0
   static_map: true
   rolling_window: false
   resolution: 0.1
   transform_tolerance: 1.0
   map_type: costmap